//
//  ImageManagerTests.swift
//  ImageManagerTests
//
//  Created by NVR4GET
//

import XCTest
@testable import ImageManager

#if canImport(UIKit)
import UIKit
#elseif canImport(AppKit)
import AppKit
#endif

final class ImageManagerTests: XCTestCase {
    
    var manager: ImageManager!
    var testDirectory: URL!
    
    override func setUp() async throws {
        // Create temporary test directory
        let tempDir = FileManager.default.temporaryDirectory
        testDirectory = tempDir.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: testDirectory, withIntermediateDirectories: true)
        
        // Initialize manager with test directory
        let config = ImageManagerConfig(
            maxCacheSize: 10_000_000,  // 10MB for tests
            maxCacheCount: 10,
            baseURL: testDirectory
        )
        manager = ImageManager(config: config)
    }
    
    override func tearDown() async throws {
        manager = nil
        
        // Clean up test directory
        try? FileManager.default.removeItem(at: testDirectory)
    }
    
    // MARK: - Save Tests
    
    func testSaveWithAutoGeneratedFilename() async throws {
        let data = createTestImageData(width: 100, height: 100) // 1x helper from TestHelpers.swift
        
        let filename = try await manager.save(data)
        
        // Should auto-generate UUID filename
        XCTAssertTrue(filename.hasSuffix(".jpg"))
        XCTAssertTrue(filename.contains("-"))  // UUID contains dashes
        
        // Should exist
        let exists = await manager.exists(filename: filename)
        XCTAssertTrue(exists)
    }
    
    func testSaveWithCustomFilename() async throws {
        let data = createTestImageData(width: 100, height: 100) // 1x helper
        let customName = "test-image.jpg"
        
        let filename = try await manager.save(data, filename: customName)
        
        XCTAssertEqual(filename, customName)
        
        let exists = await manager.exists(filename: filename)
        XCTAssertTrue(exists)
    }
    
    func testSaveAddsToCacheAndDisk() async throws {
        let data = createTestImageData(width: 100, height: 100) // 1x helper
        
        let filename = try await manager.save(data)
        
        // Load should work (from cache)
        let result = await manager.loadData(filename: filename)
        XCTAssertTrue(result.isSuccess)
        
        // File should exist on disk
        let fileURL = testDirectory.appendingPathComponent(filename)
        XCTAssertTrue(FileManager.default.fileExists(atPath: fileURL.path))
    }
    
    // MARK: - Load Tests
    
    func testLoadDataSuccess() async throws {
        let data = createTestImageData(width: 100, height: 100) // 1x helper
        let filename = try await manager.save(data)
        
        let result = await manager.loadData(filename: filename)
        
        guard case .success(let loadedData) = result else {
            XCTFail("Expected success")
            return
        }
        
        XCTAssertEqual(loadedData, data)
    }
    
    func testLoadDataFileNotFound() async throws {
        let result = await manager.loadData(filename: "nonexistent.jpg")
        
        guard case .failure(let error) = result else {
            XCTFail("Expected failure")
            return
        }
        
        if case .fileNotFound(let filename) = error {
            XCTAssertEqual(filename, "nonexistent.jpg")
        } else {
            XCTFail("Expected fileNotFound error")
        }
    }
    
    #if canImport(UIKit)
    func testLoadUIImageSuccess() async throws {
        let data = createTestImageData(width: 100, height: 100) // 1x helper
        let filename = try await manager.save(data)
        
        let result = await manager.loadUIImage(filename: filename)
        
        guard case .success(let image) = result else {
            XCTFail("Expected success")
            return
        }
        
        XCTAssertNotNil(image)
        XCTAssertEqual(image.size.width, 100)
        XCTAssertEqual(image.size.height, 100)
    }
    
    func testLoadUIImageInvalidData() async throws {
        // Save invalid data
        let invalidData = Data("not an image".utf8)
        let filename = try await manager.save(invalidData)
        
        let result = await manager.loadUIImage(filename: filename)
        
        guard case .failure(let error) = result else {
            XCTFail("Expected failure")
            return
        }
        
        if case .invalidImageData = error {
            // Expected
        } else {
            XCTFail("Expected invalidImageData error")
        }
    }
    #endif
    
    #if canImport(AppKit) && !targetEnvironment(macCatalyst)
    func testLoadNSImageSuccess() async throws {
        let data = createTestImageData(width: 100, height: 100) // 1x helper
        let filename = try await manager.save(data)
        
        let result = await manager.loadNSImage(filename: filename)
        
        guard case .success(let image) = result else {
            XCTFail("Expected success")
            return
        }
        
        XCTAssertNotNil(image)
        XCTAssertEqual(image.size.width, 100)
        XCTAssertEqual(image.size.height, 100)
    }
    #endif
    
    func testLoadCGImageSuccess() async throws {
        let data = createTestImageData(width: 100, height: 100) // 1x helper
        let filename = try await manager.save(data)
        
        let result = await manager.loadCGImage(filename: filename)
        
        guard case .success(let cgImage) = result else {
            XCTFail("Expected success")
            return
        }
        
        XCTAssertNotNil(cgImage)
        XCTAssertEqual(cgImage.width, 100)
        XCTAssertEqual(cgImage.height, 100)
    }
    
    // MARK: - Delete Tests
    
    func testDeleteSuccess() async throws {
        let data = createTestImageData(width: 100, height: 100) // 1x helper
        let filename = try await manager.save(data)
        
        // Verify exists
        var exists = await manager.exists(filename: filename)
        XCTAssertTrue(exists)
        
        // Delete
        try await manager.delete(filename: filename)
        
        // Verify deleted
        exists = await manager.exists(filename: filename)
        XCTAssertFalse(exists)
    }
    
    func testDeleteNonexistentFile() async throws {
        do {
            try await manager.delete(filename: "nonexistent.jpg")
            XCTFail("Expected error")
        } catch let error as ImageManagerError {
            if case .fileNotFound = error {
                // Expected
            } else {
                XCTFail("Expected fileNotFound error")
            }
        }
    }
    
    func testDeleteRemovesFromCache() async throws {
        let data = createTestImageData(width: 100, height: 100) // 1x helper
        let filename = try await manager.save(data)
        
        // Load to ensure it's cached
        _ = await manager.loadData(filename: filename)
        
        // Delete
        try await manager.delete(filename: filename)
        
        // Trying to load should fail (cache cleared, file deleted)
        let result = await manager.loadData(filename: filename)
        XCTAssertTrue(result.isFailure)
    }
    
    // MARK: - Cache Tests
    
    func testClearCache() async throws {
        let data = createTestImageData(width: 100, height: 100) // 1x helper
        let filename = try await manager.save(data)
        
        // Load to cache it
        _ = await manager.loadData(filename: filename)
        
        // Clear cache
        manager.clearCache()
        
        // Should still load from disk
        let result = await manager.loadData(filename: filename)
        XCTAssertTrue(result.isSuccess)
    }
    
    func testRemoveFromCache() async throws {
        let data = createTestImageData(width: 100, height: 100) // 1x helper
        let filename = try await manager.save(data)
        
        // Remove from cache
        manager.removeFromCache(filename: filename)
        
        // Should still load from disk
        let result = await manager.loadData(filename: filename)
        XCTAssertTrue(result.isSuccess)
    }
    
    // MARK: - Exists Tests
    
    func testExists() async throws {
        let data = createTestImageData(width: 100, height: 100) // 1x helper
        let filename = try await manager.save(data)
        
        let exists = await manager.exists(filename: filename)
        XCTAssertTrue(exists)
    }
    
    func testNotExists() async throws {
        let exists = await manager.exists(filename: "nonexistent.jpg")
        XCTAssertFalse(exists)
    }
}

